[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/github-data"
  to = "/.netlify/functions/github-data"
  status = 200

[[redirects]]
  from = "/api/roast"
  to = "/.netlify/functions/roast"
  status = 200

[[redirects]]
  from = "/api/roast-generic"
  to = "/.netlify/functions/roast-generic"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/google818d236dac24fe44.html"
  to = "/google818d236dac24fe44.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
